### ISSUE TITLE
Fix cowponder --version

### ISSUE THREAD

**Issue by maxcai314** [maxcai314/cowponder#8]
The `cowponder -v` version checker should not be hard coded.
for homebrew, it should do the equivalent terminal command `brew info cowponder` which actually checks the status of the installed package. In linux, it should run either `dpkg -s cowponder` or `dpkg -s cowponder | grep Status`.

Sample outputs:
dpkg -s cowponder
```
Package: cowponder
Status: install ok installed
Maintainer: Max Cai <maxster@xz.ax>
Architecture: all
Version: 0.0.1
Depends: cowsay, python3
Description: A fun little command to print a randomly selected philosophical thought from a cow
Homepage: https://github.com/maxcai314/cowponder
```

brew info cowponder
```
==> maxcai314/cowponder/cowponder: stable 0.0.2
Simple terminal command to display random philosophical thoughts from a cow
https://github.com/maxcai314/homebrew-cowponder
/usr/local/Cellar/cowponder/0.0.2 (4 files, 6.5KB) *
  Built from source on 2023-09-27 at 19:35:48
From: https://github.com/maxcai314/homebrew-cowponder/blob/HEAD/Formula/cowponder.rb
==> Dependencies
Required: cowsay ✔, python@3 ✘
```

**Comment by maxcai314** [comment]
I assume there's a similar thing with windows, idk

**Comment by reid23** [comment]
on windows, `Get-Module -n cowponder` returns:
```
Name                           Version          Source                           ProviderName
----                           -------          ------                           ------------
cowponder                      0.0.1            https://www.powershellgallery.c… PowerShellGet
```
I think this is good enough, especially since on windows `man cowponder` works to give the synopsis and docs.

**Comment by reid23** [comment]
@maxcai314 could you test the new homebrew versions, then generate all the install files? Then I think this will become ready to merge.
